---
title: "campaign finance"
output:
---

FEC bulk data URL https://www.fec.gov/
Data from the 2021 - 2022 election cycle

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
transactions <- read_csv("data/transactions.csv")
transactions_types <- read_csv("data/transaction_types.csv")
candidates <- read_csv("data/candidates.csv")
```

What transactions types are we working with
```{r}
transactions %>% 
  count(transaction_tp)
```

Join to transaction_types
Test first
```{r}
transactions_types %>% 
  count (transaction_tp) %>% 
  filter(n>1)

#no duplicate
```

Use a left join
```{r}
# Use filter(is.na(transaction_tp)) to check nulls
transactions %>% 
  left_join(transactions_types, by = "transaction_tp") %>% 
  filter(is.na(transaction_tp))

transactions %>% 
  left_join(transactions_types, by = "transaction_tp") %>% 
  count(transaction_tp, transaction_desc)
#Exactly 10896 rows. Good sign, now check nulls on the left table 

#Optional step is to create a new table from the join
transactions2 <- transactions %>% 
  left_join(transactions_types, by = "transaction_tp")
```

How much money was spent each transaction type
```{r}
transactions %>% 
  left_join(transactions_types, by = "transaction_tp") %>% 
  group_by(transaction_desc) %>% 
  summarise(total_amt = sum(transaction_amt)) %>% 
  arrange(desc(total_amt))

```

Which candidates are in our data
```{r}
transactions %>% 
  count(cand_id) %>% 
  arrange(desc(n)) %>% 
  left_join(candidates, by = "cand_id")
```

