---
title: "Opioid deaths"
output: html_notebook
---

Data from CDC WONDER
Group by state, year
1999-2020 (Multiple Cause of Death Final)

```{r}
library(tidyverse) 
library(janitor)
```

Load the data
```{r}
opioid_deaths <- read_delim("data/opioid-deaths-state-year.txt", delim="\t")
opioid_deaths <- read_tsv("data/opioid-deaths-state-year.txt")

#delim is an option argument to let you say what the argument is
```

Remove the notes
```{r}
notes<-opioid_deaths %>% 
  filter(!is.na(Notes)) %>% 
  select(Notes)

opioid_deaths <- opioid_deaths %>% 
  filter(is.na(Notes)) %>% 
  select(-Notes)
```

Transform numbers
```{r}
opioid_deaths %>% 
  count(Deaths) %>% 
  arrange(desc(Deaths))
```

Look at the "Suppressed" values
```{r}
opioid_deaths %>% 
  filter(Deaths=="Suppressed")
```

Create a numberic column for deaths
```{r}
opioid_deaths %>% 
  mutate(num_deaths = parse_number(Deaths)) %>% 
  arrange(desc(Deaths))

opioid_deaths <- opioid_deaths %>%
  mutate(num_deaths = parse_number(Deaths)) 

#Parse number: pull out number (as a Charachter variable) and return as number variable value. From tidyverse 
```

Clean the column names
```{r}
opioid_deaths <- clean_names(opioid_deaths) #Give all column names an underscore下划线
```


